### ISSUE TITLE
拷贝下来运行出错的问题！

### ISSUE THREAD

**Issue by sanshengshui** [nosqlcoco/springboot-netty-protobuf#2]
你好，我在浏览github时，无意中看到了你的项目。这个项目有我没有接触过的技术。本着学习的态度观摩你的项目，但是我拷贝下来运行时出现了错误。请你指导一下，哪里出错了。谢谢origin master!

server:
2017-04-06 10:29:11.576java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
 	at sun.nio.ch.SocketDispatcher.read0(Native Method)
 INFO	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
9556	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
---	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:366)
[ntLoopGroup-3-1]	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
c.n.server.handler.AuthServerHandler    	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
 :	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
 我是验证处理逻辑
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
2017-04-06 10:29:11.576	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
 	at java.lang.Thread.run(Thread.java:745)
ERROR 9556 --- [ntLoopGroup-3-1] c.n.server.handler.LogicServerHandler    : Connection closed, client is 123456789

**Comment by nosqlcoco** [comment]
我把连接异常打印输出了，你可以注释掉https://github.com/nosqlcoco/springboot-netty-protobuf/blob/master/src/main/java/com/netty/server/handler/LogicServerHandler.java#L80

**Comment by sanshengshui** [comment]
我试试啊！ 😎

2017-04-06 16:26 GMT+08:00 nosqlcoco <notifications@github.com>:

**Comment by sanshengshui** [comment]
​注释#80之后出现了如下情况，server不保异常了，但无法进行逻辑。client出错


2017-04-06 16:42 GMT+08:00 james mu <lovewsic@gmail.com>:

**Comment by wslyy99** [comment]
@Override
	public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
		Attribute<String> attr = ctx.attr(clientInfo);
		String clientId = attr.get();
		log.error("Connection closed, client is " + clientId);
		//cause.printStackTrace();
	}

确实是服务端报楼主提出的错误，为什么进入这个异常？难道你那里没有问题吗？

**Comment by sanshengshui** [comment]
具体情况是这样的，我用tcp_udp工具测试的时候 分别测试了这个项目的服务器端和客户端。request和response是没有问题的。具体情况出现在 当第一次客户端发送消息之后 服务器端也收到消息了。但随后客户端就自动关闭了，服务器也没有紧跟着发第二条消息。秉承着严谨的态度，对前几个月提交的问题做个回应。所以这个项目还是有点问题的。

**Comment by loveslikey** [comment]
确实有问题

**Comment by nosqlcoco** [comment]
@sanshengshui 问题已解决，你试试，问题在 NettyClient.java 中首次连接成功后关闭了channel，所以netty server 输出 “ 你的主机中的软件中止了一个已建立的连接。”

**Comment by nosqlcoco** [comment]
我先关闭这个issue，如果还有问题reopen下。
